### ISSUE TITLE
Set up redirection for old broken links referenced from Rundeck GUI

### ISSUE THREAD

**Issue by gschueler** [rundeck/docs#194]
**Describe the bug**
Some links in the rundeck GUI go to out of date URLs.  We can update the links in the rundeck app, but older versions of the app will still link to the broken URLs.  

We should add redirects (somehow) from old URLs to new URLs.

We can set up some pages that exist at the old URLs that link to the correct URLs.  This will allow the user to get to the right location.

We could also set up s3 static site redirects

**Comment by ProTip** [comment]
S3 routing rules are limited to 20, so that's probably not sustainable..

I believe a good, flexible solution would be to setup CloudFront `Lambda@Edge` service to handle redirects.. We could store redirects in a `yaml` file, potentially as regular expressions, and then utilize that to patch any issues or oopsies.

Ideally we would be able to easily validate external help links(or any links) in Rundeck prior to release. Consolidating the links into a constants file could help with that. Then, we can fallback on the redirect service for anything that slips through..

**Comment by fdevans** [comment]
Will be solved under #487
